        echo "Dostępne opcje:"
        echo "  --help -h         Wyświetl pomoc"
        echo "  --init         Sklonuj repo"
        echo "  --date -d       Wyświetl dzisiejszą datę"
        echo "  --logs [liczba] -l    Utwórz pliki logx.txt (domyślnie 100)"
        echo "  --e [liczba] -e    Utwórz pliki error.txt (domyślnie 100)"
        echo "Stworzono $liczba plikow"